# Generated by Django 5.1.15 on 2026-07-06 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_pipelinestage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin', models.URLField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('source', models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('job_board', 'Job board'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='jobs.pipelinestage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.jobopening')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
